### ISSUE TITLE
open_api key access issue

### ISSUE THREAD

**Issue by Mir-Tasleem** [ChinarQAI/Bot_Bot#4]
The code is showing the following error on passing the api key directly :
"raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable"

**Comment by sahreen-haider** [comment]
Please Create a .env file and store the key into it.

**Comment by Mir-Tasleem** [comment]
answer as expected
